apiVersion: policies.kubewarden.io/v1
kind: AdmissionPolicy
metadata:
  name: deny-quay
spec:
  module: ghcr.io/kubewarden/policies/trusted-repos:v0.2.0
  rules:
    - apiGroups:
        - ''
      apiVersions:
        - v1
      resources:
        - pods
      operations:
        - CREATE
        - UPDATE
    - apiGroups:
        - ''
      apiVersions:
        - v1
      resources:
        - replicationcontrollers
      operations:
        - CREATE
        - UPDATE
    - apiGroups:
        - apps
      apiVersions:
        - v1
      resources:
        - deployments
        - replicasets
        - statefulsets
        - daemonsets
      operations:
        - CREATE
        - UPDATE
    - apiGroups:
        - batch
      apiVersions:
        - v1
      resources:
        - jobs
        - cronjobs
      operations:
        - CREATE
        - UPDATE
  mutating: false
  settings:
    registries:
      reject:
        - quay.io
